#!/usr/bin/env ruby
# ^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'round-three',
         path: '.'

cookbook "rsnapshot",
         git: "https://github.com/umts/rsnapshot.git"

cookbook "shibboleth",
         git: "https://github.com/umts/chef-shibboleth.git"

cookbook "ssl",
         git: "https://github.com/VendaTech/chef-cookbook-ssl.git"

# cookbook 'round-three-test',
#          path: 'test/cookbooks/round-three-test'
